"""A Netrunner card"""
type Card {
  advancementCost: Int
  agendaPoints: Int
  baseLink: Int
  cost: Int
  cycle: String
  deckLimit: Int
  faction: Faction
  factionCost: Int
  flavor: String
  id: String!
  illustrator: String
  influenceLimit: Int
  keywords: String
  memoryCost: Int
  minimumDeckSize: Int
  pack: String!
  position: Int
  quantity: Int
  side: Side!
  strength: Int
  text: String
  title: String!
  trashCost: Int
  type: Type!
  uniqueness: Boolean!
}

"""The faction a card belongs to"""
enum Faction {
  ADAM
  APEX
  ANARCH
  CRIMINAL
  HAASBIOROID
  JINTEKI
  NBN
  NEUTRALCORP
  NEUTRALRUNNER
  SHAPER
  SUNNYLEBEAU
  WEYLANDCONSORTIUM
}

"""The player side a card belongs to"""
enum Side {
  CORP
  RUNNER
}

"""The main card type"""
enum Type {
  AGENDA
  ASSET
  EVENT
  HARDWARE
  ICE
  IDENTITY
  OPERATION
  PROGRAM
  RESOURCE
  UPGRADE
}

"""The card properties available to advanced search"""
input Filter {
  advancementCost: Int
  agendaPoints: Int
  baseLink: Int
  cost: Int
  deckLimit: Int
  faction: Faction
  factionCost: Int
  flavor: String
  id: String
  illustrator: String
  influenceLimit: Int
  keywords: String
  memoryCost: Int
  minimumDeckSize: Int
  pack: String
  position: Int
  quantity: Int
  side: Side
  strength: Int
  text: String
  trashCost: Int
  type: Type
  uniqueness: Boolean
}

type Query {
  """Search for cards"""
  searchCards(
    """Includes only cards that match all fields specified"""
    filter: Filter,
    """Fields to use in fuzzy search (default: title)"""
    fuzzyFields: [String],
    """Returns cards that fuzzy match on fuzzyFields"""
    fuzzySearch: String,
    """Determines sort fields on matched Cards (default: title)"""
    orderBy: [String],
    """Excludes cards that match all fields specified"""
    reject: Filter
  ): [Card]
  """Return a list of unique values for a field"""
  getDistinct(field: String!): [Card]
}
